# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
env = UnityEnvironment(file_name='Reacher_Linux/Reacher.x86_64')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 20
Size of each action: 4
There are 20 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726624e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [5]:
env_info = env.reset(train_mode=True)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
print(states)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1    
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    print('action:',actions,'reward:',rewards)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

[[ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
  -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
   1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  7.90150833e+00 -1.00000000e+00
   1.25147629e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
  -5.22214413e-01]
 [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
  -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
   1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  7.95617676e+00 -1.0000

action: [[-1.          0.27062657 -0.79809908  0.22691652]
 [-0.72510192  1.          0.84862274 -0.44227622]
 [ 0.35167069 -0.35736211  0.22928961 -0.6149215 ]
 [ 1.         -0.61353087  1.          0.25429203]
 [-1.          1.         -1.         -0.90362227]
 [-0.34504173  0.13478954 -0.34142808  1.        ]
 [-0.82772944  1.         -0.22581004 -1.        ]
 [-1.         -0.57863109  1.         -1.        ]
 [-0.28916234  0.16083849  0.68519427  0.49332651]
 [-0.52736293  1.         -0.4342734  -0.31664415]
 [ 0.60748156  0.56790308  1.         -0.51782139]
 [-0.15704053  1.          0.37255214  0.35051392]
 [-0.41874896  1.          1.         -0.9544456 ]
 [ 0.80727953 -0.9330849  -0.66673813 -0.91613604]
 [-1.         -0.83425399  1.          1.        ]
 [-0.71756126 -0.87853959 -0.26385847 -1.        ]
 [-1.         -0.36935757  1.         -0.20005672]
 [-0.07343861 -1.         -0.05784236 -0.17664253]
 [-1.         -0.96497169  1.          1.        ]
 [ 0.5334741  -0.458788

action: [[-0.77906641 -0.73353334 -0.2878441   1.        ]
 [ 1.          0.12114375  1.         -0.63953459]
 [ 1.         -1.          1.          1.        ]
 [ 1.          0.73121052 -0.98994069  1.        ]
 [-1.          0.60857114 -0.46971865 -1.        ]
 [-0.40719339 -0.64035724  1.         -0.72116158]
 [-0.06008892  0.53665078  1.         -1.        ]
 [ 0.38119084 -0.16769954 -0.20989403 -1.        ]
 [-0.03347079  0.46393234 -0.62279334  1.        ]
 [-0.0601766   1.         -1.         -1.        ]
 [-0.83058308  0.962503   -1.         -1.        ]
 [ 0.204043    1.          0.41298832 -0.9599368 ]
 [-1.         -0.39499221 -1.          1.        ]
 [-0.2299269   1.          1.          1.        ]
 [-0.81680768 -0.2890549  -0.02661944 -0.48303551]
 [-0.71337426  0.27129447 -1.         -0.02144873]
 [ 0.76815277 -0.3688448   0.03736828 -0.13218818]
 [-0.31668858 -0.11521611  1.         -1.        ]
 [-0.37940005  1.         -0.069029   -0.55354062]
 [-1.         -0.425036

action: [[-1.00000000e+00 -6.34694307e-01  2.15460943e-01 -7.67746747e-02]
 [ 2.30196587e-01  1.00000000e+00 -3.02269349e-01  1.00000000e+00]
 [ 4.21532387e-02  1.06468195e-02  2.21282936e-01 -3.25512351e-01]
 [-3.98567426e-02  2.48198159e-01 -5.07451953e-01  1.00000000e+00]
 [-1.00000000e+00 -4.43419381e-02  6.66982281e-01 -1.00000000e+00]
 [ 3.15019304e-01  4.07293960e-01 -8.27825765e-01  1.00000000e+00]
 [ 8.93060210e-02  2.53106081e-01 -1.00000000e+00  3.40819060e-01]
 [-4.56118738e-01  3.23548293e-01 -6.29112669e-01 -8.37951766e-01]
 [-1.00000000e+00  1.00000000e+00  3.64036400e-01 -3.33926994e-01]
 [ 6.57589522e-01 -4.80597657e-01 -1.00000000e+00 -6.25612196e-01]
 [ 1.00000000e+00 -8.70242417e-01 -7.35250067e-01  1.00000000e+00]
 [-9.56780268e-01  2.13160352e-01  2.13936983e-01 -5.65451888e-01]
 [-5.76143100e-01 -9.88374172e-01  3.94199427e-01 -4.76939782e-01]
 [ 5.87706250e-01  5.67557070e-01  8.84922292e-01  2.62897702e-01]
 [-5.55758552e-01 -6.93129892e-01 -1.00000000e+00  1.0

 [ 5.51008020e-01  4.94262394e-02  3.20933563e-01 -8.21833079e-01]] reward: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
action: [[ 1.         -0.24073698 -1.          1.        ]
 [-1.          0.47755938  1.         -0.12518757]
 [-0.14313837 -0.65733623  0.23041491 -0.27244413]
 [-0.26201463  0.63600825  0.90856004  0.60472191]
 [-1.         -1.         -1.          1.        ]
 [-0.17791124  0.78602931 -0.12551309  0.51767329]
 [-1.          0.54501172 -0.10810278  0.24185987]
 [ 0.69862147 -0.2530014   0.97040285  1.        ]
 [-1.         -0.46328044  1.         -1.        ]
 [ 0.20849974  1.         -1.         -1.        ]
 [ 1.          0.72321171  0.53647076  0.14890596]
 [-0.75296053  0.23903478  1.          1.        ]
 [ 1.          0.38361111 -0.09729138 -0.3853886 ]
 [-0.17111723 -0.85098814  1.          0.71433227]
 [-0.71587381 -0.25353026 -0.30594381  0.10569385]
 [-1.          0.99994117  1.          1.        ]

action: [[-0.31783645 -0.26889927 -1.         -0.48499388]
 [ 1.         -0.44192875 -0.70202878 -0.91066442]
 [ 0.22515459 -0.09678861  1.         -1.        ]
 [-0.41979387 -0.45403406  0.17077384  0.01071668]
 [-0.2266382   0.48985262  0.63585331  1.        ]
 [-0.70713151 -0.35980213  0.53297712  0.39243385]
 [ 1.         -1.         -0.69422803  1.        ]
 [-1.         -0.92051868 -1.          0.38641597]
 [ 0.96239439 -0.3333481  -1.          1.        ]
 [ 0.72213966 -0.21347038  0.44871602 -0.29756472]
 [ 0.57605803 -0.32163696 -1.         -1.        ]
 [ 1.         -0.70973925 -0.04287487  0.29289969]
 [ 0.31173638 -0.52738327 -1.          0.21501826]
 [ 0.51728808  1.         -0.97627434 -0.94013711]
 [-0.02002908 -1.         -0.67794392  1.        ]
 [-1.          1.          1.         -1.        ]
 [-1.          0.12311065 -0.02558309  1.        ]
 [ 1.         -0.50463889 -0.16791697 -0.79330776]
 [-0.79028725  1.         -1.         -0.90992126]
 [-1.          1.      

action: [[ 0.90744403  0.26174664 -0.98682118 -0.26611549]
 [-0.12537933  0.43762239  0.14153449  0.88981564]
 [-1.         -0.55739603 -0.05341309  1.        ]
 [-1.         -1.         -0.7748826   1.        ]
 [-0.63118006 -0.32638481  0.64990462  0.12300797]
 [ 0.6946003  -0.322647   -0.07035898  0.67794179]
 [ 0.50300312  0.65344898 -1.          0.78386612]
 [-0.11019044 -0.81201817  0.07608463 -0.77939431]
 [ 0.85056505 -0.35282206  0.26670479  0.64355147]
 [ 1.          0.63575408  0.56372585  0.46786497]
 [-1.          0.0267646  -1.          1.        ]
 [ 1.         -1.          0.50443537  1.        ]
 [ 1.         -0.03698535  1.         -0.52437619]
 [ 0.26199259  0.48823596  0.58791159  1.        ]
 [-0.46768231  1.          0.63959943  1.        ]
 [-0.1729695  -0.04468888  0.04986654 -1.        ]
 [-0.81655224  0.71334078  0.04029962  0.4096584 ]
 [ 0.11228828 -1.         -0.01727107 -0.76798996]
 [ 1.          0.83644943  0.27023779 -0.10721754]
 [-0.71285691  0.257756

action: [[ 0.02750762  0.24591988 -1.         -0.01367488]
 [-0.16273178 -0.80910228  0.64162552 -0.39954921]
 [ 1.          0.03234732 -1.         -0.46236611]
 [-0.92986058 -0.17043776  0.56553537  0.43884779]
 [-0.70257325  1.         -1.          0.41443633]
 [-1.          1.          0.50998923 -0.64901444]
 [-0.60902743  0.51752239  0.1957502   1.        ]
 [-1.         -0.31092141  0.4194218  -1.        ]
 [ 0.49220287  0.07388482  1.         -0.75194857]
 [-0.56468988  0.60167763 -1.          1.        ]
 [ 0.75230557  0.99204703 -0.60067528 -0.08096374]
 [-0.11143774 -1.         -0.05877155  0.07021467]
 [-0.77900371  0.33675986  0.26398491 -0.38867708]
 [-1.         -0.01397551  0.37710563 -0.05745786]
 [-0.64125452 -1.         -1.          0.75977095]
 [ 0.60637258 -0.33163293 -0.52024837  1.        ]
 [ 1.          1.          1.          0.30982245]
 [-0.06881984  0.52506561 -0.59264593  0.16029036]
 [-0.32059116 -1.          0.92382574 -1.        ]
 [ 0.03973807  0.644917

action: [[-0.76692455  0.93859231 -0.74701336  0.10990214]
 [-0.94840694  1.          0.65150155 -0.32266721]
 [-0.34741839  1.         -1.          0.46083724]
 [ 0.29833476  0.81034327 -0.60615664  1.        ]
 [-1.          0.22819058  0.35444937 -0.59664651]
 [ 1.          1.          0.58437481 -1.        ]
 [ 1.         -1.         -0.05365368 -0.5250611 ]
 [-0.66044146 -0.91704235 -0.3315409   1.        ]
 [-0.93618753  0.60647336  1.         -0.24732696]
 [ 0.18561099  0.01947533 -0.93955199 -0.03446265]
 [ 0.13940753 -0.58246143 -0.42615055 -0.30132094]
 [ 0.82685691  0.23355587 -0.01252409  0.89193845]
 [ 1.          0.41196983 -0.42280706 -0.4453156 ]
 [-1.         -1.          0.4645958   0.25768616]
 [-1.         -1.          0.34142744  0.92330061]
 [ 1.         -0.69722408 -1.         -0.37487755]
 [ 0.0817881   0.81714923  0.38608567  0.88213508]
 [-0.64681598 -0.85414069 -0.85515453 -0.40511278]
 [-0.43519074 -0.19653282  0.37739375  0.01394963]
 [ 0.28915628 -1.      

action: [[ 0.34944972 -0.55931491 -0.16524814  0.91318948]
 [ 1.         -0.02246861  0.93552013 -0.23893247]
 [-1.          0.97375069  1.          1.        ]
 [ 0.84726466  0.56332059 -0.30223543 -0.41637977]
 [ 0.96467025 -1.         -1.          1.        ]
 [ 1.          1.          1.         -0.01028863]
 [ 1.         -0.34460454  0.1514471   0.53668227]
 [-1.         -0.94073864  0.0814558   0.6079825 ]
 [ 1.          0.72671035 -0.32895725 -0.68405117]
 [-1.          0.43495679 -0.61287633 -0.48237513]
 [ 1.          0.35655731 -0.41535544 -1.        ]
 [-0.19696142 -0.15369994  0.11683249 -0.4889002 ]
 [ 1.         -1.          1.         -1.        ]
 [-0.94044918  1.          0.27438844  0.01956231]
 [-0.62300967 -1.         -1.          1.        ]
 [ 1.         -0.62233125 -0.40344138 -1.        ]
 [ 1.         -0.05796307  1.          0.39590879]
 [ 0.32861359 -0.24992434 -0.3166208   0.20922414]
 [-1.         -1.          0.79635671 -0.11752774]
 [ 0.13479523  0.322514

action: [[ 0.62364709 -0.42965151 -0.09802498 -0.29348566]
 [ 1.          0.71889199 -0.37982928 -0.78686724]
 [-0.05819499  0.12728346  0.09294455 -1.        ]
 [-0.28371643 -0.00601759  0.393916   -0.73382777]
 [-0.13564232  1.          1.          0.54835335]
 [-0.17134643 -0.72420421 -0.90447224 -0.49376793]
 [-0.614403   -0.64616682 -0.71899509 -0.14116479]
 [-0.99982851 -0.6837961  -1.          0.68886941]
 [ 0.3438046   0.3955146   0.23917309 -0.890052  ]
 [-0.27802059 -0.50027347 -0.39002594 -0.61324037]
 [-1.          0.39409173  0.41322864 -0.69066659]
 [-1.         -0.45330464  0.37354752  0.80384194]
 [ 1.         -1.         -1.          1.        ]
 [-1.          1.         -1.          0.9667838 ]
 [-0.58496612  0.16087459 -0.16703637 -0.26325839]
 [ 1.         -0.30563984 -0.03425329  1.        ]
 [ 0.53742042  0.4716225   1.         -0.79841053]
 [ 0.6156465   1.          0.26170808 -1.        ]
 [ 0.22353608  0.51886633  0.34235175  1.        ]
 [ 0.52785246  0.653778

action: [[-0.02772929 -1.          1.          1.        ]
 [-0.64829072 -1.          0.64354522  1.        ]
 [-0.10139873  0.61860771  1.          1.        ]
 [-1.          1.          0.80685175  0.14313208]
 [ 0.88446293 -0.4580558  -0.25025081 -0.80112401]
 [ 0.00745256  0.75303434 -0.14132829 -0.79191932]
 [ 1.          0.46924007 -1.          0.58950867]
 [-1.          0.76831461 -1.          1.        ]
 [-1.         -0.29423034  0.41169992  0.54811144]
 [-0.60383296  0.09833485 -0.39997849 -1.        ]
 [ 0.68215402 -0.69979557 -0.12117944 -0.5897673 ]
 [ 1.         -0.09245341 -1.         -0.68168186]
 [-1.          0.98158291  0.36515111  0.33991605]
 [-0.31018499  0.33001337 -0.52306519  0.16850244]
 [ 0.19780977 -1.          0.44892294  0.3621186 ]
 [-0.37051273  0.81251688  0.43764382 -0.85099488]
 [-0.13361418  1.          0.1564694  -0.34376124]
 [-0.90256801 -0.72546174  1.          0.6631447 ]
 [-1.         -0.26102756 -0.21968675 -0.68948566]
 [-0.8866805   1.      

action: [[ 0.18601873  0.65466146  0.73053244  0.40072668]
 [ 0.0352832  -0.18224241  0.2148563  -0.6168238 ]
 [-0.28181491 -0.59095218  0.38750635  0.74047237]
 [ 0.59161333  1.          0.67761154  0.83236239]
 [-0.20349289 -0.74263135 -0.75355711  0.53332712]
 [ 0.47379986 -1.          1.          0.9524254 ]
 [ 1.          0.15870994  0.47004959 -0.2651515 ]
 [ 1.         -0.34748248  0.19842827 -0.61432965]
 [ 1.         -0.59466547  0.33783653 -0.08542685]
 [-1.         -0.74135608  0.27781165  0.39715249]
 [-1.          0.11834472 -0.95615592  0.26696687]
 [-0.23376593  1.         -0.81845626 -0.04568776]
 [ 0.12324354  0.49585509 -0.04121541  0.99678261]
 [-0.83679622  0.13384802  1.          0.96271425]
 [-1.         -0.69307309 -1.          0.97914972]
 [-1.          0.73324375  1.         -0.32828761]
 [-1.          0.31389773 -1.         -0.8960706 ]
 [-1.         -0.17795724  1.          0.31550776]
 [ 0.38883977 -0.50899653  1.         -1.        ]
 [ 0.67822099 -1.      

action: [[-1.00000000e+00 -5.56115764e-01  4.77239523e-01  6.93460208e-01]
 [-3.41241263e-02 -1.76075244e-02 -1.00000000e+00  9.64526100e-01]
 [ 3.43660451e-01  1.00000000e+00 -9.43200318e-01  6.55114433e-01]
 [-7.39540796e-02 -7.41559767e-01 -3.40029553e-01 -7.53519126e-01]
 [-3.77877285e-01 -4.00061018e-01  1.00000000e+00 -1.00000000e+00]
 [ 1.82841249e-01  1.44509186e-01  1.00000000e+00  3.91743707e-01]
 [-4.14835825e-01 -9.67849938e-01  1.00000000e+00 -8.45974342e-04]
 [ 1.00000000e+00 -5.49961461e-02 -1.30103290e-01  4.94995106e-01]
 [-7.49447812e-01 -1.00000000e+00 -6.42530245e-01  1.00000000e+00]
 [ 2.88199093e-01  1.53676310e-01 -5.54489727e-01  7.41827278e-01]
 [ 3.46955769e-02 -1.00000000e+00 -7.97570705e-01  6.29137989e-01]
 [-1.00000000e+00  1.00000000e+00 -1.00000000e+00  8.76928484e-02]
 [-1.00000000e+00  7.84176933e-01  3.41765174e-01 -6.93808117e-01]
 [ 1.00000000e+00 -1.00000000e+00  6.76922515e-01 -1.00000000e+00]
 [-6.26257768e-01 -3.37371264e-01  1.11051161e-01 -2.7

action: [[-0.82103959  0.36031997  0.87499812 -0.85914767]
 [-0.99139302 -0.52139382  1.         -0.80016927]
 [ 0.15225273 -0.6898211   0.24073567 -1.        ]
 [ 0.45165487 -1.          1.         -0.60036918]
 [ 0.50311554  1.          0.24634327 -1.        ]
 [-0.83733245  1.          0.61015133 -0.81023471]
 [-0.90483475  0.37357337 -1.         -0.765404  ]
 [ 1.          0.67673851 -1.          1.        ]
 [ 0.01963146  0.19187115  0.41574744 -0.59128963]
 [-0.61691107 -0.18681619 -0.96795105 -0.3996602 ]
 [ 1.         -0.0871387   0.1530252  -1.        ]
 [ 1.          0.16271481  0.60500377  0.79590283]
 [-0.01354316 -1.          0.07813399  1.        ]
 [-0.26920409  0.64327751  1.          0.27444322]
 [ 0.84358754  0.26126971  0.98964049  0.27018169]
 [ 0.96374636 -0.73498654  1.         -0.95092555]
 [-0.52501845  0.59625784  0.13901039  0.11510335]
 [ 0.20264485 -0.51220846  0.37230889  0.26599858]
 [-0.08254594  0.17081792  0.22187251  0.88442073]
 [-0.31617631 -0.621102

action: [[-1.         -0.37576252 -0.42809788 -0.12924368]
 [-0.40913157  1.         -0.76351658  1.        ]
 [-0.97295156 -1.         -0.22107891  0.07243121]
 [ 0.56630538 -0.45228065 -1.          0.36281865]
 [ 1.          1.          0.3785562   0.90963603]
 [-1.         -1.          0.31644542 -0.01100256]
 [-1.          0.03558742 -1.          1.        ]
 [-1.         -0.1548969   0.99793969 -0.62189619]
 [ 0.64317655  0.53061208  0.224187    1.        ]
 [ 1.         -1.          0.72252395  0.50701427]
 [-1.          1.          1.          1.        ]
 [ 1.         -0.36514008 -0.20969652  0.97998386]
 [-1.          1.          0.43973752 -0.2330754 ]
 [-1.         -0.71874293  1.         -0.79995433]
 [-0.96626305 -1.         -0.22454071 -0.22100936]
 [ 0.7627272   1.         -0.36112067 -1.        ]
 [-1.          0.66816576  0.17126288  0.71221181]
 [-0.90957346  1.          1.          0.88070109]
 [ 0.39659492 -1.          0.44099543 -1.        ]
 [-0.41470014  0.836146

When finished, you can close the environment.

In [6]:
#env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

### Continueous Control REINFORCE

- State size 33. Action size=4  
- We start with a Class Policy representing Pi(A|S) where A is a vector of the action (len = number of total action = 4). The input size of NN Pi(A|S) is the same as state size =33.
- Calculate Reward fn of a trajectory R

In [7]:
import torch
torch.manual_seed(0) # set random seed
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Categorical
from collections import deque
from ddpg_agent import Agent

env_info = env.reset(train_mode=True)[brain_name]
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


In [8]:
import torchvision.transforms as transforms

In [9]:
def ddpg(n_episodes=1000, max_t = 1000, print_every=100,env=env,brain_name=brain_name):
    scores_window = deque(maxlen=100)
    scores = np.zeros(num_agents)
    scores_episode = []
    
    agents =[] 
    
    for i in range(num_agents):
        agents.append(Agent(state_size, action_size, random_seed=0))
    
    for i_episode in range(1, n_episodes+1):
        env_info = env.reset(train_mode=True)[brain_name]
        states = env_info.vector_observations
        
        for agent in agents:
            agent.reset()
            
        scores = np.zeros(num_agents)
            
        for t in range(max_t):
            #actions = [agents[i].act(states[i]) for i in range(num_agents)]
            actions = np.array([agents[i].act(states[i]) for i in range(num_agents)])
#             if t == 0:
#                 print("actions", actions)
            env_info = env.step(actions)[brain_name]        # send the action to the environment
            next_states = env_info.vector_observations     # get the next state
            rewards = env_info.rewards                     # get the reward
            dones = env_info.local_done        
            
            for i in range(num_agents):
                agents[i].step(t,states[i], actions[i], rewards[i], next_states[i], dones[i]) 
 
            states = next_states
            scores += rewards
            if t % 20:
                print('\rTimestep {}\tScore: {:.2f}\tmin: {:.2f}\tmax: {:.2f}'
                      .format(t, np.mean(scores), np.min(scores), np.max(scores)), end="") 
            if np.any(dones):
                break 
        score = np.mean(scores)
        scores_window.append(score)       # save most recent score
        scores_episode.append(score)

        print('\rEpisode {}\tScore: {:.2f}\tAverage Score: {:.2f}'.format(i_episode, score, np.mean(scores_window)), end="\n")
        if i_episode % 100 == 0:
            print('\rEpisode {}\tAverage Score: {:.2f}'.format(i_episode, np.mean(scores_window)))
        if np.mean(scores_window)>=30.0:
            print('\nEnvironment solved in {:d} episodes!\tAverage Score: {:.2f}'.format(i_episode-100, np.mean(scores_window)))
            torch.save(Agent.actor_local.state_dict(), 'checkpoint_actor.pth')
            torch.save(Agent.critic_local.state_dict(), 'checkpoint_critic.pth')
            break
            
    return scores_episode

env_info = env.reset(train_mode=True)[brain_name] 
agent = Agent(state_size, action_size, random_seed=2)
scores = ddpg(n_episodes=1000, max_t = 1000, print_every=100,env=env,brain_name=brain_name)

fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(np.arange(1, len(scores)+1), scores)
plt.ylabel('Score')
plt.xlabel('Episode #')
plt.show()

Initialising ReplayBuffer
Episode 1	Score: 0.05	Average Score: 0.05.42
Episode 2	Score: 0.73	Average Score: 0.39.46
Episode 3	Score: 1.25	Average Score: 0.68.35
Episode 4	Score: 1.43	Average Score: 0.87.60
Episode 5	Score: 2.14	Average Score: 1.12.26
Episode 6	Score: 2.97	Average Score: 1.43.75
Episode 7	Score: 3.25	Average Score: 1.69.87
Episode 8	Score: 3.54	Average Score: 1.92.95
Episode 9	Score: 5.33	Average Score: 2.302.72
Episode 10	Score: 5.54	Average Score: 2.6292
Episode 11	Score: 5.83	Average Score: 2.9249
Episode 12	Score: 8.96	Average Score: 3.42.90
Episode 13	Score: 6.82	Average Score: 3.68.73
Episode 14	Score: 5.94	Average Score: 3.84.80
Episode 15	Score: 7.70	Average Score: 4.10.29
Episode 16	Score: 8.29	Average Score: 4.36.93
Episode 17	Score: 9.31	Average Score: 4.65.06
Episode 18	Score: 8.32	Average Score: 4.86.71
Episode 19	Score: 10.97	Average Score: 5.18.55
Episode 20	Score: 8.99	Average Score: 5.37.44
Episode 21	Score: 9.86	Average Score: 5.58.47
Episode 22	Score:

NameError: name 'plt' is not defined